[project]
name = "restaurant-booking-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shushmitatiwari", email = "shushmita.tiwari@powerup.money" }
]
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "pipecat-ai[cartesia,daily,deepgram,groq,livekit,runner,silero,telnyx,webrtc,websocket]>=1.8.1",
    "pymongo>=4.18.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
restaurant-booking-agent = "restaurant_booking_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
